version: "3"

volumes:
  my_data:

networks:
  dev_network:
    driver: bridge

services:
  db:
    container_name: Blackwood-Postgres
    image: postgres:latest
    volumes:
      - my_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: blackwood
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: P@ssw0rd12
    networks:
      - dev_network

  keycloak:
    container_name: Blackwood-Keycloak
    image: jboss/keycloak
    hostname: keycloak.dev
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: blackwood
      DB_USER: admin
      DB_SCHEMA: public
      DB_PASSWORD: P@ssw0rd12
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: P@ssw0rd12
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - dev_network

  Nautobot:
    container_name: Blackwood-Nautobot
    image: networktocode/nautobot-lab
    hostname: nautobot.dev
    ports:
      - "8000:8000"
    networks:
      - dev_network
