version: "3"

volumes:
  my_data:

networks:
  my_network:
    driver: bridge

services:
  db:
    image: postgres:latest
      - my_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: nautobot
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: P@ssw0rd12
    networks:
      - my_network

  Nautobot:
    image: "networktocode/nautobot"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: nautobot
      DB_USER: admin
      DB_SCHEMA: public
      DB_PASSWORD: P@ssw0rd12
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - my_network
